### ISSUE TITLE
Update Error (URL did not provide a valid manifest file)

### ISSUE THREAD

**Issue by Chaos1141** [jopeek/fvtt-loot-sheet-npc-5e#211]
**To Reproduce**

- Open Add-on Modules tab of foundry
- Select update on module

**Expected behavior**
For the Module to update (receive a valid manifest file )

**Screenshots**
![Capture](https://user-images.githubusercontent.com/94289619/147167665-ed82506b-f155-48b2-8408-346bf45490c4.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: NA it is happening inside Foundry
 - Version: 9.9

**Comment by jopeek** [comment]
Uninstall and fresh reinstall should fix it.

**Comment by Chaos1141** [comment]
Looks like I now have the latest, but when I select update (update all in this case) it stills gives the error, I assume it is trying to update to a version that doesn't exist.

**Comment by jopeek** [comment]
Not sure why that would be… 3.3.81 is the current version.

**Comment by Chaos1141** [comment]
I have 3.3.81

**Comment by jopeek** [comment]
I see. That seems to be a small bug in the build process at the moment. @DanielBoettner The downloaded manifest has these lines, with the manifest url being incorrect. It is not like that in the actual repo, so I suspect the workflow does that. 

    "manifest": "https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/latest/download/module.json",

@Chaos1141, we'll get this fixed. For now, ignore it and we'll ping you here when fixed.

**Comment by DanielBoettner** [comment]
This issue should be solved.

The **module.json** in the master branch and the generated zip now have the correct URLs.

branch
```json
"manifest": "https://raw.githubusercontent.com/jopeek/fvtt-loot-sheet-npc-5e/master/module.json",
"download": "https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/latest/download/lootsheetnpc5e.zip"
```

zip
```json
"manifest": "https://raw.githubusercontent.com/jopeek/fvtt-loot-sheet-npc-5e/master/module.json",
"download": "https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/latest/download/lootsheetnpc5e.zip"
```
Can someone confirm?

**Comment by Bud6333** [comment]
Just tried to update. Issue still persists going from previous version.

**Comment by MagicOriole** [comment]
The error message no longer pops for me. Thanks!

**Comment by jopeek** [comment]
> Just tried to update. Issue still persists going from previous version. I will remain at the older version to test again when needed.

I don't think your currently installed version will fix itself but if you uninstall and reinstall 3.3.82 from the package manager, it should work. Would you mind trying that and then clicking Update after to see if it doesn't throw an error anymore?

**Comment by Bud6333** [comment]
Yes, uninstalling and reinstalling fixes the issue.

**Comment by jopeek** [comment]
Resolved in 3.3.82
