### ISSUE TITLE
Cannot buy inventory

### ISSUE THREAD

**Issue by iksior** [jopeek/fvtt-loot-sheet-npc-5e#393]
**Describe the bug**
After clicking on buy icon from account with observer account nothing is happenning and error is being displayed in console
**To Reproduce**
1. Create new NPC
2. Change sheet to Loot sheet npc 
3. Add observer permission for a player
3. add item from inventory to npc inventory
4. relog to player account
5. click on npc token 
6. after clicking on BUY icon nothing is happening but error is being displayed in console
`Uncaught TypeError: undefined. Cannot read properties of null (reading '_id')
[Detected 1 package: lootsheet-simple]
    at LootSheet5eNPC._buyItem (lootsheet-simple.js:626:30)
    at HTMLAnchorElement.<anonymous> (lootsheet-simple.js:307:47)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)`

**Expected behavior**
Item should be added to player inv

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 
 - Version Version 110.0.5481.177 (Official Build) (arm64)

**Additional context**

**Comment by jopeek** [comment]
Confirmed. Will release a fix asap.

**Comment by jopeek** [comment]
Fixed in 5.04.

**Comment by iksior** [comment]
Retested:


Should I create a new issue?
Current version: 5.04

Error still exists.
Same repro
`lootsheet-simple.js:626 Uncaught TypeError: undefined. Cannot read properties of null (reading '_id')
[Detected 1 package: lootsheet-simple]
    at LootSheet5eNPC._buyItem (lootsheet-simple.js:626:30)
    at HTMLAnchorElement.<anonymous> (lootsheet-simple.js:307:47)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)`
